#!/bin/sh

BASE=$(dirname $0)
WEBROOT=$(pwd)
CONFIG="{
  \"webRoot\": \"$WEBROOT\",
  \"staticFiles\": \"$BASE/static\"
}"

# Make a temporary file and stash the config JSON
TMP_FILE=$(mktemp /tmp/collide.XXXXXXXXXX) || { echo "Failed to create temp file"; exit 1; }
echo $CONFIG >> $TMP_FILE

#TODO: Make the ant build generate this string.
COLLIDE_CLASSPATH=$BASE:$BASE/lib/gwt-user.jar:$BASE/lib/collide-server.jar:$BASE/lib/guava-12.0.jar:$BASE/lib/gson-2.2.1.jar:$BASE/lib/jsr305.jar:$BASE/lib/org.eclipse.jgit-1.3.0.201202151440-r.jar:$BASE/lib/waveinabox-import-0.3.jar

# Launch the server, setting up the appropriate classpath and config files.
${BASE}/lib/vertx/bin/vertx run bootstrap.js -conf $TMP_FILE -cp $COLLIDE_CLASSPATH "$@"
