#!/bin/sh


BASE=$(readlink $0)
if [ -z "$BASE" ]; then
BASE=.
else
BASE=$(dirname $BASE)
fi

ant dist

cd $BASE/bin/deploy

rsync -avz -e ssh ./static/* ajaxian@wetheinter.net:/home/ajaxian/collide/static/
rsync -avz -e ssh ./lib/*.jar ajaxian@wetheinter.net:/home/ajaxian/collide/lib/

cd -
rsync -avz -e ssh ./* ajaxian@wetheinter.net:/home/ajaxian/source/
#rsync -avz -e ssh ./demo/* ajaxian@wetheinter.net:/home/ajaxian/source/demo/
#rsync -avz -e ssh ./plugin/* ajaxian@wetheinter.net:/home/ajaxian/source/plugin/

ssh ajaxian@wetheinter.net
cd $BASE


