#!/bin/sh
#
# API tests are tests that poke at the event bus API of a verticle.
# This script is simply a convenience for setting up the classpath.

BASE=$(dirname $0)
VERTX=$1
TEST_NAME=$2
CLASSPATH_ROOT=$3
TEST_ROOT=$4

#TODO: Make the ant build generate this string.
JAR_DEPS=$TEST_ROOT/lib/collide-server.jar:$TEST_ROOT/lib/vertx/lib/vertx-lang-rhino-1.2.3.final.jar:$TEST_ROOT/lib/guava-12.0.jar:$TEST_ROOT/lib/gson-2.2.1.jar:$TEST_ROOT/lib/jsr305.jar:$TEST_ROOT/lib/org.eclipse.jgit-1.3.0.201202151440-r.jar:$TEST_ROOT/lib/waveinabox-import-0.3.jar

# Run the test.
cd $BASE
${VERTX}/bin/vertx run $TEST_NAME -cp $BASE:$CLASSPATH_ROOT:$JAR_DEPS "$@"
